// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PeriodicTasks.DbContext;

#nullable disable

namespace PeriodicTasks.DbContext.PostgreSql.Migrations
{
    [DbContext(typeof(TaskSchedulerContext))]
    [Migration("20230106105633_TSInitial")]
    partial class TSInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ITVComponents.Plugins.DatabaseDrivenConfiguration.Models.DatabasePlugin", b =>
                {
                    b.Property<int>("PluginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PluginId"));

                    b.Property<string>("Constructor")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool?>("Disabled")
                        .HasColumnType("boolean");

                    b.Property<string>("DisabledReason")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<int>("LoadOrder")
                        .HasColumnType("integer");

                    b.Property<string>("TenantId")
                        .HasColumnType("text");

                    b.Property<string>("UniqueName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("PluginId");

                    b.HasIndex(new[] { "TenantId" }, "IX_PlugInTenant");

                    b.ToTable("Plugins", (string)null);
                });

            modelBuilder.Entity("PeriodicTasks.DatabaseDrivenTaskLoading.Models.PeriodicLog", b =>
                {
                    b.Property<int>("PeriodicLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PeriodicLogId"));

                    b.Property<DateTime>("LogTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<int>("MessageType")
                        .HasColumnType("integer");

                    b.Property<int>("PeriodicRunId")
                        .HasColumnType("integer");

                    b.Property<int?>("PeriodicStepId")
                        .HasColumnType("integer");

                    b.Property<string>("TenantId")
                        .HasColumnType("text");

                    b.HasKey("PeriodicLogId");

                    b.HasIndex("PeriodicRunId");

                    b.HasIndex("PeriodicStepId");

                    b.HasIndex(new[] { "TenantId" }, "IX_LogMessageTenant");

                    b.ToTable("PeriodicLog", (string)null);
                });

            modelBuilder.Entity("PeriodicTasks.DatabaseDrivenTaskLoading.Models.PeriodicMonth", b =>
                {
                    b.Property<int>("PeriodicMonthId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PeriodicMonthId"));

                    b.Property<bool>("Apr")
                        .HasColumnType("boolean");

                    b.Property<bool>("Aug")
                        .HasColumnType("boolean");

                    b.Property<bool>("Dec")
                        .HasColumnType("boolean");

                    b.Property<bool>("Feb")
                        .HasColumnType("boolean");

                    b.Property<bool>("Jan")
                        .HasColumnType("boolean");

                    b.Property<bool>("Jul")
                        .HasColumnType("boolean");

                    b.Property<bool>("Jun")
                        .HasColumnType("boolean");

                    b.Property<bool>("Mar")
                        .HasColumnType("boolean");

                    b.Property<bool>("May")
                        .HasColumnType("boolean");

                    b.Property<bool>("Nov")
                        .HasColumnType("boolean");

                    b.Property<bool>("Oct")
                        .HasColumnType("boolean");

                    b.Property<int>("PeriodicScheduleId")
                        .HasColumnType("integer");

                    b.Property<bool>("Sep")
                        .HasColumnType("boolean");

                    b.Property<string>("TenantId")
                        .HasColumnType("text");

                    b.HasKey("PeriodicMonthId");

                    b.HasIndex("PeriodicScheduleId");

                    b.HasIndex(new[] { "TenantId" }, "IX_ScheduleMonthTenant");

                    b.ToTable("PeriodicMonths", (string)null);
                });

            modelBuilder.Entity("PeriodicTasks.DatabaseDrivenTaskLoading.Models.PeriodicMonthday", b =>
                {
                    b.Property<int>("PeriodicMonthdayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PeriodicMonthdayId"));

                    b.Property<int>("DayNum")
                        .HasColumnType("integer");

                    b.Property<int>("PeriodicScheduleId")
                        .HasColumnType("integer");

                    b.Property<string>("TenantId")
                        .HasColumnType("text");

                    b.HasKey("PeriodicMonthdayId");

                    b.HasIndex("PeriodicScheduleId");

                    b.HasIndex(new[] { "TenantId" }, "IX_ScheduleMonthDayTenant");

                    b.ToTable("PeriodicMonthdays", (string)null);
                });

            modelBuilder.Entity("PeriodicTasks.DatabaseDrivenTaskLoading.Models.PeriodicRun", b =>
                {
                    b.Property<int>("PeriodicRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PeriodicRunId"));

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PeriodicTaskId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TenantId")
                        .HasColumnType("text");

                    b.HasKey("PeriodicRunId");

                    b.HasIndex("PeriodicTaskId");

                    b.HasIndex(new[] { "TenantId" }, "IX_RunTenant");

                    b.ToTable("PeriodicRuns", (string)null);
                });

            modelBuilder.Entity("PeriodicTasks.DatabaseDrivenTaskLoading.Models.PeriodicSchedule", b =>
                {
                    b.Property<int>("PeriodicScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PeriodicScheduleId"));

                    b.Property<DateTime>("FirstDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Mod")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Occurrence")
                        .HasColumnType("integer");

                    b.Property<bool>("OnServiceStart")
                        .HasColumnType("boolean");

                    b.Property<string>("Period")
                        .HasColumnType("text");

                    b.Property<int>("PeriodicTaskId")
                        .HasColumnType("integer");

                    b.Property<string>("SchedulerName")
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .HasColumnType("text");

                    b.HasKey("PeriodicScheduleId");

                    b.HasIndex("PeriodicTaskId");

                    b.HasIndex(new[] { "TenantId" }, "IX_ScheduleTenant");

                    b.ToTable("PeriodicSchedules", (string)null);
                });

            modelBuilder.Entity("PeriodicTasks.DatabaseDrivenTaskLoading.Models.PeriodicStep", b =>
                {
                    b.Property<int>("PeriodicStepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PeriodicStepId"));

                    b.Property<string>("Command")
                        .HasColumnType("text");

                    b.Property<string>("ExclusiveAreaName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("OutputVariable")
                        .HasColumnType("text");

                    b.Property<int>("PeriodicTaskId")
                        .HasColumnType("integer");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer");

                    b.Property<string>("TenantId")
                        .HasColumnType("text");

                    b.Property<string>("WorkerName")
                        .HasColumnType("text");

                    b.HasKey("PeriodicStepId");

                    b.HasIndex("PeriodicTaskId");

                    b.HasIndex(new[] { "TenantId" }, "IX_StepTenant");

                    b.ToTable("PeriodicSteps", (string)null);
                });

            modelBuilder.Entity("PeriodicTasks.DatabaseDrivenTaskLoading.Models.PeriodicStepParameter", b =>
                {
                    b.Property<int>("PeriodicStepParameterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PeriodicStepParameterId"));

                    b.Property<string>("ParameterName")
                        .HasColumnType("text");

                    b.Property<string>("ParameterType")
                        .HasColumnType("text");

                    b.Property<int>("PeriodicStepId")
                        .HasColumnType("integer");

                    b.Property<string>("Settings")
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("PeriodicStepParameterId");

                    b.HasIndex("PeriodicStepId");

                    b.HasIndex(new[] { "TenantId" }, "IX_StepParamTenant");

                    b.ToTable("PeriodicStepParameters", (string)null);
                });

            modelBuilder.Entity("PeriodicTasks.DatabaseDrivenTaskLoading.Models.PeriodicTask", b =>
                {
                    b.Property<int>("PeriodicTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PeriodicTaskId"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ExclusiveAreaName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("TenantId")
                        .HasColumnType("text");

                    b.HasKey("PeriodicTaskId");

                    b.HasIndex(new[] { "TenantId" }, "IX_TaskTenant");

                    b.ToTable("PeriodicTasks", (string)null);
                });

            modelBuilder.Entity("PeriodicTasks.DatabaseDrivenTaskLoading.Models.PeriodicTime", b =>
                {
                    b.Property<int>("PeriodicTimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PeriodicTimeId"));

                    b.Property<int>("PeriodicScheduleId")
                        .HasColumnType("integer");

                    b.Property<string>("TenantId")
                        .HasColumnType("text");

                    b.Property<string>("Time")
                        .HasColumnType("text");

                    b.HasKey("PeriodicTimeId");

                    b.HasIndex("PeriodicScheduleId");

                    b.HasIndex(new[] { "TenantId" }, "IX_ScheduleTimeTenant");

                    b.ToTable("PeriodicTimes", (string)null);
                });

            modelBuilder.Entity("PeriodicTasks.DatabaseDrivenTaskLoading.Models.PeriodicWeekday", b =>
                {
                    b.Property<int>("PeriodicWeekdayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PeriodicWeekdayId"));

                    b.Property<bool>("Friday")
                        .HasColumnType("boolean");

                    b.Property<bool>("Monday")
                        .HasColumnType("boolean");

                    b.Property<int>("PeriodicScheduleId")
                        .HasColumnType("integer");

                    b.Property<bool>("Saturday")
                        .HasColumnType("boolean");

                    b.Property<bool>("Sunday")
                        .HasColumnType("boolean");

                    b.Property<string>("TenantId")
                        .HasColumnType("text");

                    b.Property<bool>("Thursday")
                        .HasColumnType("boolean");

                    b.Property<bool>("Tuesday")
                        .HasColumnType("boolean");

                    b.Property<bool>("Wednesday")
                        .HasColumnType("boolean");

                    b.HasKey("PeriodicWeekdayId");

                    b.HasIndex("PeriodicScheduleId");

                    b.HasIndex(new[] { "TenantId" }, "IX_ScheduleWeekDayTenant");

                    b.ToTable("PeriodicWeekDays", (string)null);
                });

            modelBuilder.Entity("PeriodicTasks.DatabaseDrivenTaskLoading.Models.PeriodicLog", b =>
                {
                    b.HasOne("PeriodicTasks.DatabaseDrivenTaskLoading.Models.PeriodicRun", "PeriodicRun")
                        .WithMany("PeriodicLogs")
                        .HasForeignKey("PeriodicRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PeriodicTasks.DatabaseDrivenTaskLoading.Models.PeriodicStep", "PeriodicStep")
                        .WithMany("PeriodicLogs")
                        .HasForeignKey("PeriodicStepId");

                    b.Navigation("PeriodicRun");

                    b.Navigation("PeriodicStep");
                });

            modelBuilder.Entity("PeriodicTasks.DatabaseDrivenTaskLoading.Models.PeriodicMonth", b =>
                {
                    b.HasOne("PeriodicTasks.DatabaseDrivenTaskLoading.Models.PeriodicSchedule", "PeriodicSchedule")
                        .WithMany("PeriodicMonths")
                        .HasForeignKey("PeriodicScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PeriodicSchedule");
                });

            modelBuilder.Entity("PeriodicTasks.DatabaseDrivenTaskLoading.Models.PeriodicMonthday", b =>
                {
                    b.HasOne("PeriodicTasks.DatabaseDrivenTaskLoading.Models.PeriodicSchedule", "PeriodicSchedule")
                        .WithMany("PeriodicMonthdays")
                        .HasForeignKey("PeriodicScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PeriodicSchedule");
                });

            modelBuilder.Entity("PeriodicTasks.DatabaseDrivenTaskLoading.Models.PeriodicRun", b =>
                {
                    b.HasOne("PeriodicTasks.DatabaseDrivenTaskLoading.Models.PeriodicTask", "PeriodicTask")
                        .WithMany("PeriodicRuns")
                        .HasForeignKey("PeriodicTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PeriodicTask");
                });

            modelBuilder.Entity("PeriodicTasks.DatabaseDrivenTaskLoading.Models.PeriodicSchedule", b =>
                {
                    b.HasOne("PeriodicTasks.DatabaseDrivenTaskLoading.Models.PeriodicTask", "PeriodicTask")
                        .WithMany("PeriodicSchedules")
                        .HasForeignKey("PeriodicTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PeriodicTask");
                });

            modelBuilder.Entity("PeriodicTasks.DatabaseDrivenTaskLoading.Models.PeriodicStep", b =>
                {
                    b.HasOne("PeriodicTasks.DatabaseDrivenTaskLoading.Models.PeriodicTask", "PeriodicTask")
                        .WithMany("PeriodicSteps")
                        .HasForeignKey("PeriodicTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PeriodicTask");
                });

            modelBuilder.Entity("PeriodicTasks.DatabaseDrivenTaskLoading.Models.PeriodicStepParameter", b =>
                {
                    b.HasOne("PeriodicTasks.DatabaseDrivenTaskLoading.Models.PeriodicStep", "PeriodicStep")
                        .WithMany("PeriodicStepParameters")
                        .HasForeignKey("PeriodicStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PeriodicStep");
                });

            modelBuilder.Entity("PeriodicTasks.DatabaseDrivenTaskLoading.Models.PeriodicTime", b =>
                {
                    b.HasOne("PeriodicTasks.DatabaseDrivenTaskLoading.Models.PeriodicSchedule", "PeriodicSchedule")
                        .WithMany("PeriodicTimes")
                        .HasForeignKey("PeriodicScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PeriodicSchedule");
                });

            modelBuilder.Entity("PeriodicTasks.DatabaseDrivenTaskLoading.Models.PeriodicWeekday", b =>
                {
                    b.HasOne("PeriodicTasks.DatabaseDrivenTaskLoading.Models.PeriodicSchedule", "PeriodicSchedule")
                        .WithMany("PeriodicWeekdays")
                        .HasForeignKey("PeriodicScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PeriodicSchedule");
                });

            modelBuilder.Entity("PeriodicTasks.DatabaseDrivenTaskLoading.Models.PeriodicRun", b =>
                {
                    b.Navigation("PeriodicLogs");
                });

            modelBuilder.Entity("PeriodicTasks.DatabaseDrivenTaskLoading.Models.PeriodicSchedule", b =>
                {
                    b.Navigation("PeriodicMonthdays");

                    b.Navigation("PeriodicMonths");

                    b.Navigation("PeriodicTimes");

                    b.Navigation("PeriodicWeekdays");
                });

            modelBuilder.Entity("PeriodicTasks.DatabaseDrivenTaskLoading.Models.PeriodicStep", b =>
                {
                    b.Navigation("PeriodicLogs");

                    b.Navigation("PeriodicStepParameters");
                });

            modelBuilder.Entity("PeriodicTasks.DatabaseDrivenTaskLoading.Models.PeriodicTask", b =>
                {
                    b.Navigation("PeriodicRuns");

                    b.Navigation("PeriodicSchedules");

                    b.Navigation("PeriodicSteps");
                });
#pragma warning restore 612, 618
        }
    }
}
